# Generated by Django 3.0.6 on 2022-03-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactformmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmessage',
            options={'verbose_name': 'Contact Form Message', 'verbose_name_plural': 'Contact Form Message'},
        ),
    ]
