# Generated by Django 3.0.6 on 2022-03-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220330_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='images',
            new_name='image',
        ),
    ]
