# Generated by Django 3.0.6 on 2022-03-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
