# Generated by Django 3.0.6 on 2022-03-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
