# Generated by Django 3.0.6 on 2022-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=1, upload_to='video/%y'),
            preserve_default=False,
        ),
    ]
