# Generated by Django 3.0.6 on 2022-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_ordervideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervideo',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='Open', max_length=10),
        ),
    ]
